_target_: lfads_torch.model.MRLFADS

# --------- sequence length --------- #
num_other_areas: 3
encod_seq_len: 500
recon_seq_len: 500
ic_enc_seq_len: 50

# --------- augmentation --------- #
train_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.modules.augmentations.AreaCoordinatedDropout
      cd_rate: 0.0
      cd_pass_rate: 0.0
      ic_enc_seq_len: ${model.ic_enc_seq_len}
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack

# --------- learning rate --------- #
lr_init: 4.0e-3
lr_stop: 1.0e-5
lr_decay: 0.95
lr_patience: 6
lr_adam_beta1: 0.9
lr_adam_beta2: 0.999
lr_adam_epsilon: 1.0e-8
lr_scheduler: True

# --------- regularization --------- #
weight_decay: 0.0
l2_start_epoch: 0
l2_increase_epoch: 80
l2_ic_enc_scale: 1.0e-2
l2_ci_enc_scale: 1.0e-2
l2_gen_scale: 1.0e-2
l2_con_scale: 1.0e-2
kl_start_epoch_u: 20
kl_increase_epoch_u: 200
kl_start_epoch_m: 150
kl_increase_epoch_m: 800
kl_ic_scale: 5.0e-3
kl_co_scale: 5.0e-1
kl_com_scale: 5.0e-5

# --------- misc --------- #
variational: True
loss_scale: 1.0e+4
recon_reduce_mean: True
dropout_rate: 0.3
cell_clip: 5.0

# --------- area specification --------- #
areas_info:
    MOs5:
        # --------- architecture --------- #
        encod_data_dim: 29
        ic_enc_dim: 64
        ci_enc_dim: 64
        ci_lag: 1
        con_dim: 64
        co_dim: 4
        ic_dim: 64
        gen_dim: ${eval:${model.areas_info.MOs5.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.MOs5.encod_data_dim}
        com_dim: 4

        # --------- data --------- #
        num_neurons:
          n1: 38
        ext_input_dim: 1

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.MOs5.num_neurons.n1}
              out_features: ${model.areas_info.MOs5.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.MOs5.fac_dim}
              out_features: ${model.areas_info.MOs5.num_neurons.n1}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.MOs5.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.MOs5.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.MOs5.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
        
    MOs2/3:
        # --------- architecture --------- #
        encod_data_dim: 8
        ic_enc_dim: 32
        ci_enc_dim: 32
        ci_lag: 1
        con_dim: 32
        co_dim: 4
        ic_dim: 32
        gen_dim: ${eval:${model.areas_info.MOs2/3.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.MOs2/3.encod_data_dim}
        com_dim: 4
        
        # --------- data --------- #
        num_neurons:
          n1: 8
        ext_input_dim: 1

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.MOs2/3.num_neurons.n1}
              out_features: ${model.areas_info.MOs2/3.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.MOs2/3.fac_dim}
              out_features: ${model.areas_info.MOs2/3.num_neurons.n1}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.MOs2/3.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.MOs2/3.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.MOs2/3.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
        
    VAL:
        # --------- architecture --------- #
        encod_data_dim: 20
        ic_enc_dim: 64
        ci_enc_dim: 64
        ci_lag: 1
        con_dim: 64
        co_dim: 4
        ic_dim: 64
        gen_dim: ${eval:${model.areas_info.VAL.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.VAL.encod_data_dim}
        com_dim: 4
        
        # --------- data --------- #
        num_neurons:
          n1: 20
        ext_input_dim: 1

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.VAL.num_neurons.n1}
              out_features: ${model.areas_info.VAL.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.VAL.fac_dim}
              out_features: ${model.areas_info.VAL.num_neurons.n1}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          - _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.VAL.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.VAL.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.VAL.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
        
    VM:
        # --------- architecture --------- #
        encod_data_dim: 14
        ic_enc_dim: 32
        ci_enc_dim: 32
        ci_lag: 1
        con_dim: 32
        co_dim: 4
        ic_dim: 32
        gen_dim: ${eval:${model.areas_info.VM.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.VM.encod_data_dim}
        com_dim: 4
        
        # --------- data --------- #
        num_neurons:
          n1: 16
        ext_input_dim: 1

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.VM.num_neurons.n1}
              out_features: ${model.areas_info.VM.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.VM.fac_dim}
              out_features: ${model.areas_info.VM.num_neurons.n1}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.VM.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.VM.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.VM.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4