_target_: lfads_torch.model.MRLFADS

# --------- sequence length --------- #
num_other_areas: 2
encod_seq_len: 200
recon_seq_len: 200
ic_enc_seq_len: 50

# --------- augmentation --------- #
train_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.modules.augmentations.AreaCoordinatedDropout
      cd_rate: 0.0
      cd_pass_rate: 0.0
      ic_enc_seq_len: ${model.ic_enc_seq_len}
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack

# --------- learning rate --------- #
lr_init: 4.0e-3
lr_stop: 1.0e-5
lr_decay: 0.95
lr_patience: 6
lr_adam_beta1: 0.9
lr_adam_beta2: 0.999
lr_adam_epsilon: 1.0e-8
lr_scheduler: True

# --------- regularization --------- #
weight_decay: 0.0
l2_start_epoch: 0
l2_increase_epoch: 80
l2_ic_enc_scale: 1.0e-2
l2_ci_enc_scale: 1.0e-2
l2_gen_scale: 1.0e-2
l2_con_scale: 1.0e-2
kl_start_epoch_u: 20
kl_increase_epoch_u: 200
kl_start_epoch_m: 150
kl_increase_epoch_m: 800
kl_ic_scale: 5.0e-2
kl_co_scale: 5.0e-2
kl_com_scale: 5.0e-5

# --------- misc --------- #
variational: True
loss_scale: 1.0e+4
recon_reduce_mean: True
dropout_rate: 0.3
cell_clip: 5.0

# --------- area specification --------- #
areas_info:
    source:
        # --------- architecture --------- #
        encod_data_dim: 8
        ic_enc_dim: 16
        ci_enc_dim: 16
        ci_lag: 1
        con_dim: 16
        co_dim: 4
        ic_dim: 16
        gen_dim: ${eval:${model.areas_info.source.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.source.encod_data_dim}
        com_dim: 4

        # --------- data --------- #
        num_neurons:
          n0: 16
        ext_input_dim: 0

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.source.num_neurons.n0}
              out_features: ${model.areas_info.source.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.source.fac_dim}
              out_features: ${model.areas_info.source.num_neurons.n0}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.source.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.source.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.source.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
        
    relay:
        # --------- architecture --------- #
        encod_data_dim: 8
        ic_enc_dim: 16
        ci_enc_dim: 16
        ci_lag: 1
        con_dim: 16
        co_dim: 4
        ic_dim: 16
        gen_dim: ${eval:${model.areas_info.relay.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.relay.encod_data_dim}
        com_dim: 4
        
        # --------- data --------- #
        num_neurons:
          n0: 16
        ext_input_dim: 0

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.relay.num_neurons.n0}
              out_features: ${model.areas_info.relay.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.relay.fac_dim}
              out_features: ${model.areas_info.relay.num_neurons.n0}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.relay.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.relay.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.relay.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
        
    target:
        # --------- architecture --------- #
        encod_data_dim: 8
        ic_enc_dim: 16
        ci_enc_dim: 16
        ci_lag: 1
        con_dim: 16
        co_dim: 4
        ic_dim: 16
        gen_dim: ${eval:${model.areas_info.target.encod_data_dim} * 4}
        fac_dim: ${model.areas_info.target.encod_data_dim}
        com_dim: 4
        
        # --------- data --------- #
        num_neurons:
          n0: 16
        ext_input_dim: 0

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.target.num_neurons.n0}
              out_features: ${model.areas_info.target.encod_data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: lfads_torch.modules.readin_readout.FanInLinear
              in_features: ${model.areas_info.target.fac_dim}
              out_features: ${model.areas_info.target.num_neurons.n0}

        # --------- priors / posteriors --------- #
        reconstruction:
          _target_: lfads_torch.modules.recons.Poisson
        reconstruction_null:
          - _target_: lfads_torch.modules.recons.PoissonBPS
        co_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.target.co_dim}
        ic_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_info.target.ic_dim}
        com_prior:
          _target_: lfads_torch.modules.priors.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_info.target.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        m_post_var_min: 1.0e-4
