on_init_end_calls:
  _target_: lfads_torch.callbacks.OnInitEndCalls

on_epoch_end_calls:
  _target_: lfads_torch.callbacks.OnEpochEndCalls
  callbacks:
    - _target_: lfads_torch.callbacks.Log
      tags:
        - "lr-AdamW"
    - _target_: lfads_torch.callbacks.InferredRatesPlot
      log_every_n_epochs: 10
      plot_first_session: False
    - _target_: lfads_torch.callbacks.PSTHPlot
      log_every_n_epochs: 10
    - _target_: lfads_torch.callbacks.ProctorSummaryPlot
      log_every_n_epochs: 10
    - _target_: lfads_torch.callbacks.CommunicationPSTHPlot
      log_every_n_epochs: 10
  in_train: "10000"
