# on_init_end_calls:
#   _target_: lfads_torch.callbacks.OnInitEndCalls

# on_validation_epoch_end_calls:
#   _target_: lfads_torch.callbacks.OnValidationEndCalls
#   callbacks:
#     - _target_: lfads_torch.callbacks.InferredRatesPlot
#       log_every_n_epochs: 30
#     - _target_: lfads_torch.callbacks.PSTHPlot
#       log_every_n_epochs: 10
#     - _target_: lfads_torch.callbacks.ProctorSummaryPlot
#       log_every_n_epochs: 10

    
