proctor_preview_plot:
  _target_: lfads_torch.callbacks.ProctorPreviewPlot
  priority: 1

maximum_activity_units:
  _target_: lfads_torch.callbacks.MaximumActivityUnits
  priority: 1
  
psth_conditions:
  _target_: lfads_torch.callbacks.PSTHConditions
  priority: 2

inferred_rates_plot:
  _target_: lfads_torch.callbacks.InferredRatesPlot
  priority: 1
  log_every_n_epochs: 10
  
psth_plot:
  _target_: lfads_torch.callbacks.PSTHPlot
  priority: 2
  log_every_n_epochs: 10